In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [4]:
gpu = tf.config.list_physical_devices('GPU')[0]

IndexError: list index out of range

In [ ]:
# Get a small part of the memory
tf.config.experimental.set_memory_growth(gpu, True)

# Introduction to Deep Learning

In [5]:
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense

from sklearn.datasets import load_iris

In [6]:
a = tf.constant(15)
b = tf.constant(38)

In [7]:
tf.pow(tf.add(tf.multiply(2, a), tf.multiply(3, b)), 2)

<tf.Tensor: shape=(), dtype=int32, numpy=20736>

In [8]:
a = tf.constant([2, 15, 21, -244, 0, 4])
b = tf.constant([3, 2, 20, 200, 18, 15])

In [9]:
tf.pow(tf.add(tf.multiply(2, a), tf.multiply(3, b)), 2)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([  169,  1296, 10404, 12544,  2916,  2809], dtype=int32)>

In [10]:
(2 * a + 3 * b) ** 2

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([  169,  1296, 10404, 12544,  2916,  2809], dtype=int32)>

In [11]:
a = tf.random.uniform([5, 8], 0, 20)
b = tf.random.uniform([5, 8], 0, 20)

In [12]:
a, b

(<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
 array([[1.5221813e+01, 2.0042109e+00, 6.5647268e+00, 1.9273481e+01,
         9.0476274e-01, 1.2093180e+01, 1.4590656e+01, 1.9586086e-02],
        [1.3655753e+01, 5.9383202e+00, 8.0559616e+00, 1.1997046e+01,
         1.7457006e+01, 1.8403912e+01, 8.6080980e+00, 9.8098660e+00],
        [4.2902374e+00, 6.2112927e+00, 1.7076802e+00, 3.2944846e+00,
         1.9365938e+01, 5.9847546e+00, 8.2594032e+00, 3.0208373e+00],
        [1.9613987e+01, 1.6831190e+01, 1.9639757e+01, 1.6720343e+00,
         1.7796612e+00, 1.2202423e+01, 1.5530588e+01, 1.6556668e+00],
        [1.0033749e+01, 3.3072495e+00, 1.6065397e+01, 1.4599932e+01,
         4.2684031e+00, 1.0820625e+01, 6.4506793e+00, 1.3848877e+00]],
       dtype=float32)>,
 <tf.Tensor: shape=(5, 8), dtype=float32, numpy=
 array([[19.626034 ,  6.9214845,  7.9626107, 11.887409 , 19.332857 ,
          2.996688 ,  4.836085 , 10.197971 ],
        [11.540291 ,  0.6280136,  8.723452 ,  9.886492 ,  9.685483 

In [13]:
(2 * a + 3 * b) ** 2

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[7978.3716 ,  613.69543, 1370.2797 , 5507.004  , 3577.0085 ,
        1100.6749 , 1908.7783 ,  938.38605],
       [3835.6199 ,  189.35635, 1787.7911 , 2878.7053 , 4092.2202 ,
        5263.0137 , 1011.672  , 1863.6316 ],
       [4194.3066 , 1478.3016 , 1353.9016 , 4285.118  , 2688.7854 ,
         690.8066 , 1469.7699 , 1753.723  ],
       [3528.6697 , 3830.0618 , 3976.07   ,  363.5731 , 2065.1172 ,
        5099.134  , 3478.9976 , 1947.6562 ],
       [2916.9888 , 3355.6406 , 1536.6302 , 5883.973  , 1812.0632 ,
        5500.143  ,  558.1455 ,  409.08298]], dtype=float32)>

In [14]:
# Declare a function with tf
@tf.function
def compute(a, b):
  return (2 * a + 3 * b) ** 2

In [15]:
compute(a, b)

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[7978.3716 ,  613.69543, 1370.2797 , 5507.004  , 3577.0085 ,
        1100.6749 , 1908.7783 ,  938.38605],
       [3835.6199 ,  189.35634, 1787.7913 , 2878.7053 , 4092.2202 ,
        5263.0137 , 1011.672  , 1863.6316 ],
       [4194.3066 , 1478.3016 , 1353.9016 , 4285.118  , 2688.7854 ,
         690.8066 , 1469.7699 , 1753.723  ],
       [3528.6697 , 3830.0618 , 3976.07   ,  363.5731 , 2065.1172 ,
        5099.134  , 3478.9976 , 1947.6564 ],
       [2916.9888 , 3355.6406 , 1536.6302 , 5883.973  , 1812.0632 ,
        5500.143  ,  558.1455 ,  409.08298]], dtype=float32)>

In [16]:
compute(2, 3)

<tf.Tensor: shape=(), dtype=int32, numpy=169>

In [17]:
compute(tf.constant([2]), tf.constant([3]))

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([169], dtype=int32)>

In [18]:
# Extract the value
compute(tf.constant([2]), tf.constant([3])).numpy()[0]

169

In [19]:
compute(a, b) / 100000

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[0.07978372, 0.00613695, 0.0137028 , 0.05507004, 0.03577008,
        0.01100675, 0.01908778, 0.00938386],
       [0.0383562 , 0.00189356, 0.01787791, 0.02878705, 0.0409222 ,
        0.05263014, 0.01011672, 0.01863632],
       [0.04194307, 0.01478302, 0.01353902, 0.04285118, 0.02688785,
        0.00690807, 0.0146977 , 0.01753723],
       [0.0352867 , 0.03830062, 0.0397607 , 0.00363573, 0.02065117,
        0.05099134, 0.03478998, 0.01947656],
       [0.02916989, 0.03355641, 0.0153663 , 0.05883973, 0.01812063,
        0.05500143, 0.00558146, 0.00409083]], dtype=float32)>

In [20]:
x = tf.constant(5.0)

In [21]:
with tf.GradientTape() as tape:
  tape.watch(x)
  y = x ** 2
  grad_y = tape.gradient(y, x)

In [22]:
grad_y

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [23]:
with tf.GradientTape() as tape:
  tape.watch(x)
  y = tf.sin(x ** 2)
  grad_y = tape.gradient(y, x)

In [24]:
grad_y

<tf.Tensor: shape=(), dtype=float32, numpy=9.912028>

## Iris dataset

### Logistic regression

In [25]:
X, y = load_iris().data, load_iris().target

In [26]:
num_X = X.shape[1]
num_classes = len(set(y))
num_X, num_classes

(4, 3)

In [27]:
# Create a model
logistic_regression = Sequential([
    Input(num_X),
    Dense(num_classes, activation = 'softmax')
])

In [28]:
logistic_regression.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15 (60.00 Byte)
Trainable params: 15 (60.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [29]:
# Adding loss function
logistic_regression.compile(optimizer = 'sgd', loss = 'sparse_categorical_crossentropy')

In [30]:
logistic_regression.fit(X, y, epochs = 100)

Epoch 1/100
5/5 [==============================] - 0s 4ms/step - loss: 2.9218
Epoch 2/100
5/5 [==============================] - 0s 5ms/step - loss: 2.3712
Epoch 3/100
5/5 [==============================] - 0s 5ms/step - loss: 2.1234
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 2.0279
Epoch 5/100
5/5 [==============================] - 0s 6ms/step - loss: 1.9699
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 1.9085
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 1.8464
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 1.7927
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 1.7293
Epoch 10/100
5/5 [==============================] - 0s 4ms/step - loss: 1.6731
Epoch 11/100
5/5 [==============================] - 0s 4ms/step - loss: 1.6176
Epoch 12/100
5/5 [==============================] - 0s 3ms/step - loss: 1.5631
Epoch 13/100
5/5 [==============================] - 0s 3ms/st

In [31]:
logistic_regression.predict(X)

5/5 [==============================] - 0s 3ms/step


array([[0.86211705, 0.11874901, 0.01913395],
       [0.8030907 , 0.15814047, 0.03876891],
       [0.83757144, 0.13655803, 0.02587061],
       [0.7937025 , 0.16905898, 0.03723851],
       [0.86937344, 0.11414175, 0.0164848 ],
       [0.8572959 , 0.12600923, 0.01669492],
       [0.8370502 , 0.1403557 , 0.02259402],
       [0.8378429 , 0.13739778, 0.0247593 ],
       [0.7784966 , 0.17788897, 0.04361441],
       [0.80774254, 0.15594031, 0.03631712],
       [0.87346196, 0.11028028, 0.01625778],
       [0.8198631 , 0.15257597, 0.02756092],
       [0.80848193, 0.15432836, 0.03718965],
       [0.8418237 , 0.13227932, 0.02589692],
       [0.9246712 , 0.0680273 , 0.00730146],
       [0.91671324, 0.07697139, 0.00631539],
       [0.89857286, 0.09109581, 0.01033139],
       [0.856342  , 0.12374052, 0.01991751],
       [0.8591456 , 0.12211445, 0.01873992],
       [0.87170106, 0.11381326, 0.01448564],
       [0.8174592 , 0.15092261, 0.0316182 ],
       [0.857274  , 0.12527648, 0.01744947],
       [0.

## Linear regression

In [37]:
X_for_regression = X[:,:-1]
y_for_regression = X[:, -1]

In [38]:
linear_regression = Sequential([
    Input(X_for_regression.shape[1]),
    Dense(1)
])

In [39]:
linear_regression.compile(optimizer = 'sgd', loss = 'mse')

In [41]:
linear_regression.fit(X_for_regression, y_for_regression, epochs = 100)

Epoch 1/100
5/5 [==============================] - 0s 5ms/step - loss: 0.1460
Epoch 2/100
5/5 [==============================] - 0s 6ms/step - loss: 0.1321
Epoch 3/100
5/5 [==============================] - 0s 5ms/step - loss: 0.1459
Epoch 4/100
5/5 [==============================] - 0s 8ms/step - loss: 0.1376
Epoch 5/100
5/5 [==============================] - 0s 10ms/step - loss: 0.1321
Epoch 6/100
5/5 [==============================] - 0s 9ms/step - loss: 0.1335
Epoch 7/100
5/5 [==============================] - 0s 8ms/step - loss: 0.1277
Epoch 8/100
5/5 [==============================] - 0s 8ms/step - loss: 0.1248
Epoch 9/100
5/5 [==============================] - 0s 5ms/step - loss: 0.1227
Epoch 10/100
5/5 [==============================] - 0s 9ms/step - loss: 0.1243
Epoch 11/100
5/5 [==============================] - 0s 6ms/step - loss: 0.1252
Epoch 12/100
5/5 [==============================] - 0s 4ms/step - loss: 0.1223
Epoch 13/100
5/5 [==============================] - 0s 5ms/s

In [42]:
linear_regression.predict(X_for_regression)

5/5 [==============================] - 0s 3ms/step


array([[0.24009429],
       [0.35459617],
       [0.23514886],
       [0.31278208],
       [0.19629322],
       [0.2649288 ],
       [0.19432102],
       [0.28588226],
       [0.3088229 ],
       [0.35756925],
       [0.2589825 ],
       [0.2878693 ],
       [0.3396671 ],
       [0.16948663],
       [0.13654752],
       [0.10166578],
       [0.1375484 ],
       [0.24009429],
       [0.3385879 ],
       [0.18532346],
       [0.40928867],
       [0.21419536],
       [0.00919668],
       [0.39337352],
       [0.38340458],
       [0.43321535],
       [0.31772736],
       [0.28686836],
       [0.28389522],
       [0.33068416],
       [0.37448528],
       [0.3455985 ],
       [0.11363642],
       [0.0977066 ],
       [0.35756925],
       [0.248091  ],
       [0.26796532],
       [0.18136422],
       [0.24810584],
       [0.30081132],
       [0.19332011],
       [0.46513873],
       [0.19036181],
       [0.2888554 ],
       [0.31270382],
       [0.3396671 ],
       [0.21716855],
       [0.252