# Introduction to Deep Learning

In [1]:
!nvidia-smi

Mon Feb 26 23:14:22 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import tensorflow as tf


In [3]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
gpu = tf.config.list_physical_devices('GPU')[0]

In [5]:
# Get a small part of the memory
tf.config.experimental.set_memory_growth(gpu, True)

In [9]:
a = tf.constant(15)
b = tf.constant(38)

In [12]:
tf.pow(tf.add(tf.multiply(2, a), tf.multiply(3, b)), 2)

<tf.Tensor: shape=(), dtype=int32, numpy=20736>

In [13]:
a = tf.constant([2, 15, 21, -244, 0, 4])
b = tf.constant([3, 2, 20, 200, 18, 15])

In [14]:
tf.pow(tf.add(tf.multiply(2, a), tf.multiply(3, b)), 2)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([  169,  1296, 10404, 12544,  2916,  2809], dtype=int32)>

In [15]:
(2 * a + 3 * b) ** 2

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([  169,  1296, 10404, 12544,  2916,  2809], dtype=int32)>

In [17]:
a = tf.random.uniform([5, 8], 0, 20)
b = tf.random.uniform([5, 8], 0, 20)

In [18]:
a, b

(<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
 array([[10.329475  , 14.882553  ,  3.1123567 , 12.624414  ,  6.8871546 ,
         16.96988   ,  6.120496  ,  0.842731  ],
        [ 6.9967723 ,  5.3284216 , 19.504156  , 15.07062   ,  8.162853  ,
         18.249884  , 12.471697  ,  5.7844687 ],
        [10.017109  ,  0.3657055 , 18.204697  , 18.6186    ,  8.557596  ,
          0.74575424,  8.018217  , 16.45938   ],
        [10.702402  , 19.177185  ,  0.51934004, 13.245251  ,  7.655487  ,
          0.7800293 , 16.261942  ,  5.3403735 ],
        [16.97992   , 17.654772  ,  1.3704967 ,  9.546871  ,  4.9511456 ,
          7.674792  ,  0.19906044, 14.660659  ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 8), dtype=float32, numpy=
 array([[ 0.9586477 , 18.4577    ,  6.856458  ,  2.1390057 , 19.386139  ,
          4.7993517 ,  3.6928415 , 12.038586  ],
        [12.529228  , 18.606602  ,  0.67641497, 10.475294  , 16.382856  ,
         15.649717  , 10.575075  ,  0.758574  ],
        [11.265772  ,  

In [19]:
(2 * a + 3 * b) ** 2

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[ 553.89124, 7248.514  ,  717.9231 , 1002.72577, 5174.317  ,
        2336.5442 ,  543.7998 , 1428.9323 ],
       [2660.6233 , 4419.1445 , 1684.0809 , 3790.5107 , 4286.8804 ,
        6963.721  , 3211.332  ,  191.6746 ],
       [2897.8342 ,  119.65211, 3075.6309 , 6762.779  , 2732.5461 ,
        3221.3215 ,  673.61676, 6924.647  ],
       [3942.9565 , 9589.033  , 1132.689  , 5837.2637 , 2833.0627 ,
        3493.4514 , 1076.9777 , 1261.335  ],
       [5335.9917 , 1473.6632 , 2298.4204 ,  450.7583 , 1484.0206 ,
        4053.2397 , 1306.1544 , 2504.6733 ]], dtype=float32)>

In [20]:
# Declare a function with tf
@tf.function
def compute(a, b):
  return (2 * a + 3 * b) ** 2

In [21]:
compute(a, b)

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[ 553.8912 , 7248.514  ,  717.9231 , 1002.72577, 5174.317  ,
        2336.5442 ,  543.7998 , 1428.9323 ],
       [2660.6233 , 4419.1445 , 1684.0809 , 3790.5107 , 4286.8804 ,
        6963.721  , 3211.3323 ,  191.6746 ],
       [2897.8342 ,  119.65211, 3075.6309 , 6762.7783 , 2732.5461 ,
        3221.3215 ,  673.61676, 6924.647  ],
       [3942.9565 , 9589.033  , 1132.689  , 5837.263  , 2833.063  ,
        3493.4514 , 1076.9777 , 1261.335  ],
       [5335.992  , 1473.6632 , 2298.4204 ,  450.7583 , 1484.0205 ,
        4053.2397 , 1306.1544 , 2504.6733 ]], dtype=float32)>

In [22]:
compute(2, 3)

<tf.Tensor: shape=(), dtype=int32, numpy=169>

In [26]:
compute(tf.constant([2]), tf.constant([3]))

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([169], dtype=int32)>

In [27]:
# Extract the value
compute(tf.constant([2]), tf.constant([3])).numpy()[0]

169

In [28]:
compute(a, b) / 100000

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[0.00553891, 0.07248514, 0.00717923, 0.01002726, 0.05174317,
        0.02336544, 0.005438  , 0.01428932],
       [0.02660623, 0.04419145, 0.01684081, 0.03790511, 0.0428688 ,
        0.06963721, 0.03211332, 0.00191675],
       [0.02897834, 0.00119652, 0.03075631, 0.06762778, 0.02732546,
        0.03221321, 0.00673617, 0.06924647],
       [0.03942956, 0.09589034, 0.01132689, 0.05837263, 0.02833063,
        0.03493451, 0.01076978, 0.01261335],
       [0.05335992, 0.01473663, 0.0229842 , 0.00450758, 0.01484021,
        0.0405324 , 0.01306154, 0.02504673]], dtype=float32)>

In [38]:
x = tf.constant(5.0)

In [41]:
with tf.GradientTape() as tape:
  tape.watch(x)
  y = x ** 2
  grad_y = tape.gradient(y, x)

In [42]:
grad_y

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [43]:
with tf.GradientTape() as tape:
  tape.watch(x)
  y = tf.sin(x ** 2)
  grad_y = tape.gradient(y, x)

In [44]:
grad_y

<tf.Tensor: shape=(), dtype=float32, numpy=9.912028>