In [10]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


# Introduction to Deep Learning

In [11]:
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense

from sklearn.datasets import load_iris

In [12]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [13]:
gpu = tf.config.list_physical_devices('GPU')[0]

IndexError: list index out of range

In [14]:
# Get a small part of the memory
tf.config.experimental.set_memory_growth(gpu, True)

NameError: name 'gpu' is not defined

In [15]:
a = tf.constant(15)
b = tf.constant(38)

In [16]:
tf.pow(tf.add(tf.multiply(2, a), tf.multiply(3, b)), 2)

<tf.Tensor: shape=(), dtype=int32, numpy=20736>

In [17]:
a = tf.constant([2, 15, 21, -244, 0, 4])
b = tf.constant([3, 2, 20, 200, 18, 15])

In [18]:
tf.pow(tf.add(tf.multiply(2, a), tf.multiply(3, b)), 2)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([  169,  1296, 10404, 12544,  2916,  2809], dtype=int32)>

In [19]:
(2 * a + 3 * b) ** 2

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([  169,  1296, 10404, 12544,  2916,  2809], dtype=int32)>

In [20]:
a = tf.random.uniform([5, 8], 0, 20)
b = tf.random.uniform([5, 8], 0, 20)

In [21]:
a, b

(<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
 array([[ 2.525394 , 14.110312 , 15.842509 ,  1.6108727, 17.60418  ,
          8.688843 ,  1.9765782,  4.3224382],
        [19.195843 , 19.384838 , 15.11945  , 19.057732 , 13.940056 ,
         17.644417 ,  0.9425044,  1.2906456],
        [13.665662 , 11.985825 , 17.408348 , 13.843908 ,  5.8288884,
          3.650589 , 11.01506  ,  8.827801 ],
        [ 5.806763 , 13.07097  ,  6.3495517,  9.8624115,  0.3851843,
          7.0407844, 18.324032 , 13.048868 ],
        [ 6.9619584, 15.1429   , 12.577834 , 17.048513 , 15.323179 ,
         14.9272995,  8.643372 ,  2.2662306]], dtype=float32)>,
 <tf.Tensor: shape=(5, 8), dtype=float32, numpy=
 array([[19.659939  , 18.65444   ,  8.771887  , 14.973288  , 14.007961  ,
          2.2310638 ,  0.46063662,  5.3653812 ],
        [ 1.2681055 ,  8.214447  ,  9.126382  , 17.466383  , 16.243118  ,
          5.7319546 , 14.762244  , 11.222507  ],
        [10.19146   , 14.621094  ,  3.7354112 , 10.491764  , 11

In [22]:
(2 * a + 3 * b) ** 2

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[4099.918   , 7086.9365  , 3364.0789  , 2317.6143  , 5964.819   ,
         579.4071  ,   28.462933,  612.1181  ],
       [1780.5027  , 4021.2107  , 3319.839   , 8192.895   , 5869.0103  ,
        2754.6433  , 2131.8298  , 1313.9764  ],
       [3353.0703  , 4601.5776  , 2118.11    , 3500.2734  , 1998.0502  ,
        2836.423   , 5307.626   , 2381.8208  ],
       [4272.18    , 2146.5898  ,  464.72314 , 1825.3336  , 3241.9136  ,
         215.71083 , 5120.892   , 3038.6357  ],
       [ 906.4008  , 4683.1147  , 2457.0496  , 8392.503   , 6296.811   ,
        2335.868   , 1005.7203  , 3547.2578  ]], dtype=float32)>

In [23]:
# Declare a function with tf
@tf.function
def compute(a, b):
  return (2 * a + 3 * b) ** 2

In [24]:
compute(a, b)

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[4099.918   , 7086.9365  , 3364.0789  , 2317.6143  , 5964.819   ,
         579.4071  ,   28.462933,  612.1181  ],
       [1780.5027  , 4021.2107  , 3319.839   , 8192.895   , 5869.0103  ,
        2754.6433  , 2131.8296  , 1313.9764  ],
       [3353.07    , 4601.5776  , 2118.11    , 3500.2734  , 1998.0502  ,
        2836.423   , 5307.626   , 2381.8208  ],
       [4272.18    , 2146.5898  ,  464.7231  , 1825.3336  , 3241.9136  ,
         215.71083 , 5120.892   , 3038.6357  ],
       [ 906.4008  , 4683.1147  , 2457.0496  , 8392.503   , 6296.811   ,
        2335.868   , 1005.7203  , 3547.2578  ]], dtype=float32)>

In [25]:
compute(2, 3)

<tf.Tensor: shape=(), dtype=int32, numpy=169>

In [26]:
compute(tf.constant([2]), tf.constant([3]))

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([169], dtype=int32)>

In [27]:
# Extract the value
compute(tf.constant([2]), tf.constant([3])).numpy()[0]

169

In [28]:
compute(a, b) / 100000

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[0.04099918, 0.07086936, 0.03364079, 0.02317614, 0.05964819,
        0.00579407, 0.00028463, 0.00612118],
       [0.01780503, 0.04021211, 0.03319839, 0.08192895, 0.0586901 ,
        0.02754643, 0.0213183 , 0.01313976],
       [0.0335307 , 0.04601578, 0.0211811 , 0.03500273, 0.0199805 ,
        0.02836423, 0.05307626, 0.02381821],
       [0.0427218 , 0.0214659 , 0.00464723, 0.01825334, 0.03241913,
        0.00215711, 0.05120892, 0.03038636],
       [0.00906401, 0.04683115, 0.02457049, 0.08392503, 0.06296811,
        0.02335868, 0.0100572 , 0.03547258]], dtype=float32)>

In [29]:
x = tf.constant(5.0)

In [30]:
with tf.GradientTape() as tape:
  tape.watch(x)
  y = x ** 2
  grad_y = tape.gradient(y, x)

In [31]:
grad_y

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [32]:
with tf.GradientTape() as tape:
  tape.watch(x)
  y = tf.sin(x ** 2)
  grad_y = tape.gradient(y, x)

In [33]:
grad_y

<tf.Tensor: shape=(), dtype=float32, numpy=9.912028>

## Iris dataset

### Logistic regression

In [57]:
X, y = load_iris().data, load_iris().target

In [58]:
num_X = X.shape[1]
num_classes = len(set(y))
num_X, num_classes

(4, 3)

In [59]:
# Create a model
logistic_regression = Sequential([
    Input(num_X),
    Dense(num_classes, activation = 'softmax')
])

In [60]:
logistic_regression.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 3)                 15        
                                                                 
Total params: 15 (60.00 Byte)
Trainable params: 15 (60.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [61]:
# Adding loss function
logistic_regression.compile(optimizer = 'sgd', loss = 'sparse_categorical_crossentropy')

In [62]:
logistic_regression.fit(X, y, epochs = 100)

Epoch 1/100
5/5 [==============================] - 0s 2ms/step - loss: 4.2656
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 3.0353
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 2.3507
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 2.1306
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 2.0420
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 1.9705
Epoch 7/100
5/5 [==============================] - 0s 1ms/step - loss: 1.9077
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 1.8439
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 1.7876
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 1.7253
Epoch 11/100
5/5 [==============================] - 0s 2ms/step - loss: 1.6758
Epoch 12/100
5/5 [==============================] - 0s 2ms/step - loss: 1.6139
Epoch 13/100
5/5 [==============================] - 0s 2ms/st

In [63]:
logistic_regression.predict(X)

5/5 [==============================] - 0s 2ms/step


array([[0.85859966, 0.11973038, 0.02166999],
       [0.79012483, 0.1711419 , 0.0387332 ],
       [0.8329215 , 0.13803068, 0.0290478 ],
       [0.7851994 , 0.17582084, 0.03897976],
       [0.8688054 , 0.11168563, 0.01950891],
       [0.86295575, 0.11509357, 0.02195074],
       [0.8404949 , 0.13080451, 0.02870064],
       [0.83199763, 0.1411379 , 0.02686439],
       [0.76876104, 0.18589342, 0.04534557],
       [0.79147303, 0.17475449, 0.03377252],
       [0.8699312 , 0.11179887, 0.01826987],
       [0.8150045 , 0.15504232, 0.02995326],
       [0.7925158 , 0.17253838, 0.03494588],
       [0.8357005 , 0.13598454, 0.02831486],
       [0.92509997, 0.06572626, 0.00917372],
       [0.9261627 , 0.06415077, 0.00968655],
       [0.90561724, 0.07935292, 0.01502979],
       [0.85632324, 0.11937494, 0.0243018 ],
       [0.8560176 , 0.12270569, 0.0212766 ],
       [0.8763737 , 0.10479061, 0.01883566],
       [0.80417055, 0.16511114, 0.03071829],
       [0.8637338 , 0.11253627, 0.02372985],
       [0.