In [6]:
%matplotlib inline

In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split
from sklearn.inspection import permutation_importance

# Support Vector Machines 

## Demos

In [96]:
attributes, labels = load_iris().data, load_iris().target

In [97]:
attributes_train,attributes_test, labels_train, labels_test = train_test_split(attributes, labels, test_size = 0.15, stratify=labels)

In [98]:
tree = DecisionTreeClassifier(min_samples_leaf = 5)

In [99]:
tree.fit(attributes_train, labels_train)

DecisionTreeClassifier(min_samples_leaf=5)

In [100]:
tree.score(attributes_train, labels_train)

0.9763779527559056

In [101]:
tree.score(attributes_test, labels_test)

0.8695652173913043

In [102]:
tree.feature_importances_

array([0.        , 0.        , 0.54281598, 0.45718402])

In [68]:
print(load_iris().DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [86]:
permutation_importance(tree, attributes_train, labels_train)

{'importances_mean': array([0.        , 0.        , 0.09291339, 0.51023622]),
 'importances_std': array([0.        , 0.        , 0.01822966, 0.03280735]),
 'importances': array([[0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.07086614, 0.08661417, 0.09448819, 0.12598425, 0.08661417],
        [0.53543307, 0.51181102, 0.49606299, 0.5511811 , 0.45669291]])}

In [87]:
permutation_importance(tree, attributes_train, labels_train)['importances_mean']

array([0.        , 0.        , 0.10708661, 0.52755906])

In [88]:
# Creating new model without first two features -a.k.a. features selection
tree_new = DecisionTreeClassifier(min_samples_leaf = 5)

In [89]:
tree_new.fit(attributes_train[:, 2:], labels_train)

DecisionTreeClassifier(min_samples_leaf=5)

In [90]:
tree_new.score(attributes_train[:, 2:], labels_train)

0.9606299212598425

In [92]:
tree_new.feature_importances_

array([0.45378121, 0.54621879])

In [95]:
permutation_importance(tree_new, attributes_train[:, 2:], labels_train,n_repeats=50)['importances_mean']

array([0.29574803, 0.43574803])