In [6]:
%matplotlib inline

In [124]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split
from sklearn.inspection import permutation_importance

from sklearn.svm import SVC

# Support Vector Machines 

## Demos

In [110]:
attributes, labels = load_iris().data, load_iris().target

In [111]:
attributes_train,attributes_test, labels_train, labels_test = train_test_split(attributes, labels, test_size = 0.15, stratify=labels)

In [112]:
tree = DecisionTreeClassifier(min_samples_leaf = 5)

In [113]:
tree.fit(attributes_train, labels_train)

DecisionTreeClassifier(min_samples_leaf=5)

In [114]:
tree.score(attributes_train, labels_train)

0.9763779527559056

In [115]:
tree.score(attributes_test, labels_test)

0.8695652173913043

In [116]:
tree.feature_importances_

array([0.        , 0.        , 0.01319849, 0.98680151])

In [68]:
print(load_iris().DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [117]:
permutation_importance(tree, attributes_train, labels_train)

{'importances_mean': array([0.        , 0.        , 0.        , 0.63307087]),
 'importances_std': array([0.        , 0.        , 0.        , 0.03093997]),
 'importances': array([[0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.62992126, 0.5984252 , 0.60629921, 0.68503937, 0.64566929]])}

In [118]:
permutation_importance(tree, attributes_train, labels_train)['importances_mean']

array([0.        , 0.        , 0.        , 0.62834646])

In [119]:
# Creating new model without first two features -a.k.a. features selection
tree_new = DecisionTreeClassifier(min_samples_leaf = 5)

In [120]:
tree_new.fit(attributes_train[:, 2:], labels_train)

DecisionTreeClassifier(min_samples_leaf=5)

In [121]:
# tree_new.score(attributes_train[:, 2:], labels_train)

In [122]:
tree_new.feature_importances_

array([0.01319849, 0.98680151])

In [123]:
permutation_importance(tree_new, attributes_train[:, 2:], labels_train,n_repeats=50)['importances_mean']

array([0.        , 0.64818898])

In [141]:
linear_svm = SVC(C = 1e9, kernel='linear')

In [142]:
linear_svm.fit(attributes_train, labels_train)

SVC(C=1000000000.0, kernel='linear')

In [143]:
linear_svm.coef_, linear_svm.intercept_

(array([[-4.61704135e-02,  5.21394693e-01, -1.00309152e+00,
         -4.64149175e-01],
        [-7.09388135e-03,  1.78890625e-01, -5.38427661e-01,
         -2.92251262e-01],
        [ 1.75748382e+00,  1.08715609e+01, -1.05321752e+01,
         -4.21003432e+01]]),
 array([ 1.45194667,  1.50728785, 82.17591202]))

In [144]:
linear_svm.support_vectors_

array([[4.5, 2.3, 1.3, 0.3],
       [4.8, 3.4, 1.9, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.9, 3.2, 4.8, 1.8],
       [6. , 2.7, 5.1, 1.6],
       [5.1, 2.5, 3. , 1.1],
       [6. , 3. , 4.8, 1.8],
       [7.2, 3. , 5.8, 1.6],
       [4.9, 2.5, 4.5, 1.7]])